/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as OrchestrationRouteImport } from './routes/orchestration'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as ListRouteImport } from './routes/list'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as DashAgentsRouteImport } from './routes/dash-agents'
import { Route as CronsRouteImport } from './routes/crons'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrationRoute = OrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/orchestration.lazy').then((d) => d.Route))
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/evolution.lazy').then((d) => d.Route))
const DashAgentsRoute = DashAgentsRouteImport.update({
  id: '/dash-agents',
  path: '/dash-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CronsRoute = CronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/content.lazy').then((d) => d.Route))
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/content': typeof ContentRoute
  '/crons': typeof CronsRoute
  '/dash-agents': typeof DashAgentsRoute
  '/evolution': typeof EvolutionRoute
  '/list': typeof ListRoute
  '/office': typeof OfficeRoute
  '/orchestration': typeof OrchestrationRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/content': typeof ContentRoute
  '/crons': typeof CronsRoute
  '/dash-agents': typeof DashAgentsRoute
  '/evolution': typeof EvolutionRoute
  '/list': typeof ListRoute
  '/office': typeof OfficeRoute
  '/orchestration': typeof OrchestrationRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/content': typeof ContentRoute
  '/crons': typeof CronsRoute
  '/dash-agents': typeof DashAgentsRoute
  '/evolution': typeof EvolutionRoute
  '/list': typeof ListRoute
  '/office': typeof OfficeRoute
  '/orchestration': typeof OrchestrationRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/channels'
    | '/config'
    | '/content'
    | '/crons'
    | '/dash-agents'
    | '/evolution'
    | '/list'
    | '/office'
    | '/orchestration'
    | '/providers'
    | '/sessions'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/channels'
    | '/config'
    | '/content'
    | '/crons'
    | '/dash-agents'
    | '/evolution'
    | '/list'
    | '/office'
    | '/orchestration'
    | '/providers'
    | '/sessions'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/channels'
    | '/config'
    | '/content'
    | '/crons'
    | '/dash-agents'
    | '/evolution'
    | '/list'
    | '/office'
    | '/orchestration'
    | '/providers'
    | '/sessions'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  ChannelsRoute: typeof ChannelsRoute
  ConfigRoute: typeof ConfigRoute
  ContentRoute: typeof ContentRoute
  CronsRoute: typeof CronsRoute
  DashAgentsRoute: typeof DashAgentsRoute
  EvolutionRoute: typeof EvolutionRoute
  ListRoute: typeof ListRoute
  OfficeRoute: typeof OfficeRoute
  OrchestrationRoute: typeof OrchestrationRoute
  ProvidersRoute: typeof ProvidersRoute
  SessionsRoute: typeof SessionsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestration': {
      id: '/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof OrchestrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash-agents': {
      id: '/dash-agents'
      path: '/dash-agents'
      fullPath: '/dash-agents'
      preLoaderRoute: typeof DashAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crons': {
      id: '/crons'
      path: '/crons'
      fullPath: '/crons'
      preLoaderRoute: typeof CronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  ChannelsRoute: ChannelsRoute,
  ConfigRoute: ConfigRoute,
  ContentRoute: ContentRoute,
  CronsRoute: CronsRoute,
  DashAgentsRoute: DashAgentsRoute,
  EvolutionRoute: EvolutionRoute,
  ListRoute: ListRoute,
  OfficeRoute: OfficeRoute,
  OrchestrationRoute: OrchestrationRoute,
  ProvidersRoute: ProvidersRoute,
  SessionsRoute: SessionsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
