/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as CronsRouteImport } from './routes/crons'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const CronsRoute = CronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/crons': typeof CronsRoute
  '/evolution': typeof EvolutionRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/crons': typeof CronsRoute
  '/evolution': typeof EvolutionRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/crons': typeof CronsRoute
  '/evolution': typeof EvolutionRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/channels'
    | '/config'
    | '/crons'
    | '/evolution'
    | '/providers'
    | '/sessions'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/channels'
    | '/config'
    | '/crons'
    | '/evolution'
    | '/providers'
    | '/sessions'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/channels'
    | '/config'
    | '/crons'
    | '/evolution'
    | '/providers'
    | '/sessions'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChannelsRoute: typeof ChannelsRoute
  ConfigRoute: typeof ConfigRoute
  CronsRoute: typeof CronsRoute
  EvolutionRoute: typeof EvolutionRoute
  ProvidersRoute: typeof ProvidersRoute
  SessionsRoute: typeof SessionsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crons': {
      id: '/crons'
      path: '/crons'
      fullPath: '/crons'
      preLoaderRoute: typeof CronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChannelsRoute: ChannelsRoute,
  ConfigRoute: ConfigRoute,
  CronsRoute: CronsRoute,
  EvolutionRoute: EvolutionRoute,
  ProvidersRoute: ProvidersRoute,
  SessionsRoute: SessionsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
