/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronsRouteImport } from './routes/crons'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'
import { Route as DashboardListRouteImport } from './routes/dashboard/list'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardBoardRouteImport } from './routes/dashboard/board'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronsRoute = CronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListRoute = DashboardListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBoardRoute = DashboardBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/crons': typeof CronsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/evolution': typeof EvolutionRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/list': typeof DashboardListRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/crons': typeof CronsRoute
  '/evolution': typeof EvolutionRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/list': typeof DashboardListRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/config': typeof ConfigRoute
  '/crons': typeof CronsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/evolution': typeof EvolutionRoute
  '/providers': typeof ProvidersRoute
  '/sessions': typeof SessionsRoute
  '/tools': typeof ToolsRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/list': typeof DashboardListRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/channels'
    | '/config'
    | '/crons'
    | '/dashboard'
    | '/evolution'
    | '/providers'
    | '/sessions'
    | '/tools'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/board'
    | '/dashboard/calendar'
    | '/dashboard/list'
    | '/dashboard/login'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/channels'
    | '/config'
    | '/crons'
    | '/evolution'
    | '/providers'
    | '/sessions'
    | '/tools'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/board'
    | '/dashboard/calendar'
    | '/dashboard/list'
    | '/dashboard/login'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/channels'
    | '/config'
    | '/crons'
    | '/dashboard'
    | '/evolution'
    | '/providers'
    | '/sessions'
    | '/tools'
    | '/dashboard/agents'
    | '/dashboard/analytics'
    | '/dashboard/board'
    | '/dashboard/calendar'
    | '/dashboard/list'
    | '/dashboard/login'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChannelsRoute: typeof ChannelsRoute
  ConfigRoute: typeof ConfigRoute
  CronsRoute: typeof CronsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EvolutionRoute: typeof EvolutionRoute
  ProvidersRoute: typeof ProvidersRoute
  SessionsRoute: typeof SessionsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crons': {
      id: '/crons'
      path: '/crons'
      fullPath: '/crons'
      preLoaderRoute: typeof CronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/list': {
      id: '/dashboard/list'
      path: '/list'
      fullPath: '/dashboard/list'
      preLoaderRoute: typeof DashboardListRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/board': {
      id: '/dashboard/board'
      path: '/board'
      fullPath: '/dashboard/board'
      preLoaderRoute: typeof DashboardBoardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBoardRoute: typeof DashboardBoardRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardListRoute: typeof DashboardListRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBoardRoute: DashboardBoardRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardListRoute: DashboardListRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChannelsRoute: ChannelsRoute,
  ConfigRoute: ConfigRoute,
  CronsRoute: CronsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EvolutionRoute: EvolutionRoute,
  ProvidersRoute: ProvidersRoute,
  SessionsRoute: SessionsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
